name: cpufetch
adopt-info: cpufetch
summary: Simple yet fancy CPU architecture fetching tool
description: |
  Simple yet fancy CPU architecture fetching tool
  
  cpufetch has a help menu: cpufetch --help
  By default, cpufetch will print the CPU art with the system colorscheme. 
  However, you can always set a custom color scheme, either specifying 
  Intel or AMD, or specifying the colors in RGB format:

  ./cpufetch --color intel (default color for Intel)
  ./cpufetch --color amd (default color for AMD)
  ./cpufetch --color 239,90,45:210,200,200:100,200,45:0,200,200 (example)
  
  For more info, see the developer's repo: https://github.com/Dr-Noob/cpufetch 
  
license: MIT
issues: https://github.com/kz6fittycent/cpufetch
source-code: https://github.com/Dr-Noob/cpufetch
contact: https://github.com/kz6fittycent/cpufetch
website: https://github.com/Dr-Noob/cpufetch
base: core24
grade: stable
confinement: strict
compression: lzo

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]
  
apps:
  cpufetch:
    command: usr/bin/cpufetch

parts:
  cpufetch:
    source: https://github.com/Dr-Noob/cpufetch
    source-type: git
    plugin: make
    build-environment:
      - PREFIX: "/usr"  
      
    override-pull: |
      craftctl default
      craftctl set version="$(git describe --tags | sed 's/^v//' | cut -d "-" -f1)"     
          
